# ============================================
# Configuration Mosquitto - Station IoT
# ============================================

# === Network ===
# Port interne TCP (utilisé par le backend Django)
listener 1883
protocol mqtt

# Port WebSocket (utilisé par Nginx Proxy Manager)
listener 9001
protocol websockets

# === Security ===
allow_anonymous true

# === Persistence ===
persistence true
persistence_location /mosquitto/data/
autosave_interval 300

# === Logging ===
log_dest stdout
log_type error
log_type warning
log_type notice
log_type information
connection_messages true
log_timestamp true
